<?php
//This file has been automatically generated by X-News v2.0.0

$script['advertising']['activenews']="NO";
$script['advertising']['archivednews']="NO";
$script['advertising']['md_active']="selected";
$script['advertising']['md_archive']="selected";
$script['advertising']['active_selad']="5";

$script['advertising']['archive_selad']="5";

$script['advertising']['active_adpos']="1 2 4";

$script['advertising']['archive_adpos']="5 6 9";

?>