<?php
function WriteConfiguration()
{
  // require("./config.inc.php");
   $advactivenews   = htmlspecialchars(@$_POST['advertising#activenews']);
   $advarchivednews = htmlspecialchars(@$_POST['advertising#archivednews']);
   if ($advactivenews!='YES')   $advactivenews='NO';
   if ($advarchivednews!='YES') $advarchivednews='NO';


   $handle=fopen("configuration/advertising.inc.php","w");
   fwrite($handle,"<?php\n");
   fwrite($handle,"//This file has been automatically generated by X-News v2.0.0\n\n");
     fwrite($handle,"\$script['advertising']['activenews']=\"".$advactivenews."\";\n");
     fwrite($handle,"\$script['advertising']['archivednews']=\"".$advarchivednews."\";\n");
     fwrite($handle,"\$script['advertising']['md_active']=\"".htmlspecialchars($_POST['md_active'])."\";\n");
     fwrite($handle,"\$script['advertising']['md_archive']=\"".htmlspecialchars($_POST['md_archive'])."\";\n");
     fwrite($handle,"\$script['advertising']['active_selad']=\"".htmlspecialchars($_POST['active_selad'])."\";\n\n");
     fwrite($handle,"\$script['advertising']['archive_selad']=\"".htmlspecialchars($_POST['archive_selad'])."\";\n\n");
     fwrite($handle,"\$script['advertising']['active_adpos']=\"".htmlspecialchars($_POST['advertising#active_adpos'])."\";\n\n");
     fwrite($handle,"\$script['advertising']['archive_adpos']=\"".htmlspecialchars($_POST['advertising#archive_adpos'])."\";\n\n");
   fwrite($handle,"?>");
   fclose($handle);
}

function ReadConfiguration($wrapper)
{
    require("config.inc.php");


    if ($script['advertising']['md_active']=='selected')
    {
     $wrapper=str_replace('check_md_active_selected','checked',$wrapper);
     $wrapper=str_replace('check_md_active_random','',$wrapper);
    }else
    {
     $wrapper=str_replace('check_md_active_random','checked',$wrapper);
     $wrapper=str_replace('check_md_active_selected','',$wrapper);
    }

    if ($script['advertising']['md_archive']=='selected')
    {
     $wrapper=str_replace('check_md_archive_selected','checked',$wrapper);
     $wrapper=str_replace('check_md_archive_random','',$wrapper);
    }else
    {
     $wrapper=str_replace('check_md_archive_random','checked',$wrapper);
     $wrapper=str_replace('check_md_archive_selected','',$wrapper);
    }

    return $wrapper;
}



?>