<?php
//This file has been automatically generated by X-News v1.0.1

$script['paths']['picturedir']="C:/Server/www/sites/el/news/images/";
$script['paths']['pictureurl']="http://localhost/sites/el/news/images/";
$script['paths']['picviewer']="http://localhost/sites/el/news/viewer.php?src=";
?>