<?php
//This file has been automatically generated by X-News v1.0.1

$script['comments']['enabled']="OFF";
$script['comments']['captcha']="ON";
$script['comments']['messagelength']="1020";
$script['comments']['html']="OFF";
$script['comments']['bbcode']="ON";

?>