<?php
//This file has been automatically generated by X-News v2.0.0

$script['news']['show_first']="5";
$script['news']['newsperpage']="5";
$script['news']['sort']="newest";
$script['news']['time_format']="F j<\s\u\p><\u>S</\u></\s\u\p>, Y \a\\t g:i A";
$script['news']['html']="ON";
$script['editor']['wysiwyg']="ON";
$script['news']['bbcode']="ON";

$script['icons']['save']="ON";
$script['icons']['path']="C:/Server/www/sites/el/news/icons/";
$script['icons']['limitwidth']="120";
$script['icons']['limitheight']="120";
$script['icons']['url']="http://localhost/sites/el/news/icons/";

?>