<?php
function WriteConfiguration()
{
   //require("./config.inc.php");
   $handle=fopen("configuration/news_comments.inc.php","w");
     if (!isset($_POST['comments#html'])){$commentshtml='OFF';} else {$commentshtml='ON';}
     if (!isset($_POST['comments#bbcode'])){$commentsbbcode='OFF';} else {$commentsbbcode='ON';}
     if (!isset($_POST['comments#captcha'])){$commentscaptcha='OFF';} else {$commentscaptcha='ON';}
     if (!isset($_POST['comments#enabled'])){$commentsenabled='OFF';} else {$commentsenabled='ON';}

   fwrite($handle,"<?php\n");
   fwrite($handle,"//This file has been automatically generated by X-News v1.0.1\n\n");
     fwrite($handle,"\$script['comments']['enabled']=\"".htmlspecialchars($commentsenabled)."\";\n");
     fwrite($handle,"\$script['comments']['captcha']=\"".htmlspecialchars($commentscaptcha)."\";\n");
     fwrite($handle,"\$script['comments']['messagelength']=\"".htmlspecialchars($_POST['comments#messagelength'])."\";\n");
     fwrite($handle,"\$script['comments']['html']=\"".htmlspecialchars($commentshtml)."\";\n");
     fwrite($handle,"\$script['comments']['bbcode']=\"".htmlspecialchars($commentsbbcode)."\";\n\n");
   fwrite($handle,"?>");
   fclose($handle);
}

function ReadConfiguration($wrapper)
{
    return $wrapper;
}


?>