<?php
function WriteConfiguration()
{
//   require("./config.inc.php");
   $handle=fopen("configuration/news_publishing.inc.php","w");
   if (!isset($_POST['news#html'])){$allowhtml='OFF';} else {$allowhtml='ON';}
   if (!isset($_POST['editor#wysiwyg'])){$allowgui='OFF';} else {$allowgui='ON';}
   if (!isset($_POST['news#bbcode'])){$allowbbcode='OFF';} else {$allowbbcode='ON';}
   if (!isset($_POST['icons#save'])){$saveicons='OFF';} else {$saveicons='ON';}
   if (!isset($_POST['news#newsperpage'])) {$newsperpage="10";} else {$newsperpage=$_POST['news#newsperpage'];}
   if (!is_numeric($newsperpage)) $newsperpage=10;
   fwrite($handle,"<?php\n");
   fwrite($handle,"//This file has been automatically generated by X-News v2.0.0\n\n");
   fwrite($handle,"\$script['news']['show_first']=\"".htmlspecialchars($_POST['news#show_first'])."\";\n");
   fwrite($handle,"\$script['news']['newsperpage']=\"".$newsperpage."\";\n");
   fwrite($handle,"\$script['news']['sort']=\"".htmlspecialchars($_POST['news#sort'])."\";\n");
   fwrite($handle,"\$script['news']['time_format']=\"".htmlspecialchars($_POST['news#time_format'])."\";\n");	// MANUALLY EDIT THE FILE LISTED ABOVE TO INCLUDE HTML TAGS -- DATE HERE!
   fwrite($handle,"\$script['news']['html']=\"".$allowhtml."\";\n");
   fwrite($handle,"\$script['editor']['wysiwyg']=\"".$allowgui."\";\n");
   fwrite($handle,"\$script['news']['bbcode']=\"".$allowbbcode."\";\n\n");
     fwrite($handle,"\$script['icons']['save']=\"".htmlspecialchars($saveicons)."\";\n");
     fwrite($handle,"\$script['icons']['path']=\"".htmlspecialchars($_POST['icons#path'])."\";\n");
     fwrite($handle,"\$script['icons']['limitwidth']=\"".htmlspecialchars($_POST['icons#limitwidth'])."\";\n");
     fwrite($handle,"\$script['icons']['limitheight']=\"".htmlspecialchars($_POST['icons#limitheight'])."\";\n");
     fwrite($handle,"\$script['icons']['url']=\"".htmlspecialchars($_POST['icons#url'])."\";\n\n");
   fwrite($handle,"?>");
   fclose($handle);
}

function ReadConfiguration($wrapper)
{
    require("config.inc.php");
    require_once("skin.php");
    if (strtolower($script['news']['sort'])=="newest")
    {
     $optcode="<option selected value=\"newest\">".LanguageField("l_newest")."</option><option value=\"oldest\">".LanguageField("l_oldest")."</option>";
    }
    else
    {
     $optcode="<option value=\"newest\">".LanguageField("l_newest")."</option><option selected value=\"oldest\">".LanguageField("l_oldest")."</option>";
    }
    $wrapper=str_replace("news|sort",$optcode,$wrapper);
    return $wrapper;
}

?>