<?php
function WriteConfiguration()
{
 //  require("./config.inc.php");
   if (!isset($_POST['rss#enabled'])){$enablerss='NO';} else {$enablerss='YES';}
   $handle=fopen("configuration/rss_engine.inc.php","w");
   fwrite($handle,"<?php\n");
   fwrite($handle,"//This file has been automatically generated by X-News v1.0.1\n\n");
   fwrite($handle,"\$script['rss']['enabled']=\"".$enablerss."\";\n\n");
   fwrite($handle,"\$script['rss']['title']=\"".htmlspecialchars($_POST['rss#title'])."\";\n");
   fwrite($handle,"\$script['rss']['description']=\"".htmlspecialchars($_POST['rss#description'])."\";\n");
   fwrite($handle,"\$script['rss']['link']=\"".htmlspecialchars($_POST['rss#link'])."\";\n");
   fwrite($handle,"?>");
   fclose($handle);
}
function ReadConfiguration($wrapper)
{
    return $wrapper;
}


?>