<?php
//This file has been automatically generated by X-News v1.0.1

$script['rss']['enabled']="NO";

$script['rss']['title']="Elemovements' News";
$script['rss']['description']="The latest news for the band.";
$script['rss']['link']="http://localhost/sites/el/news/news.php";
?>