<?php
//This file has been automatically generated by X-News v1.0.1

$script['paths']['newsurl']="http://localhost/sites/el/news/news.php";
$script['paths']['file']="C:/Server/www/sites/el/news/";
$script['paths']['url']="http://localhost/sites/el/news/";
$script['paths']['backup']="bak";
$script['system']['time_adjust']="-360";

$script['system']['language']="English";

?>