<?php
function WriteConfiguration()
{
  // require("./config.inc.php");
   $handle=fopen("configuration/script_settings.inc.php","w");
   fwrite($handle,"<?php\n");
   fwrite($handle,"//This file has been automatically generated by X-News v1.0.1\n\n");
     fwrite($handle,"\$script['paths']['newsurl']=\"".htmlspecialchars($_POST['paths#newsurl'])."\";\n");
     fwrite($handle,"\$script['paths']['file']=\"".htmlspecialchars($_POST['paths#file'])."\";\n");
     fwrite($handle,"\$script['paths']['url']=\"".htmlspecialchars($_POST['paths#url'])."\";\n");
     fwrite($handle,"\$script['paths']['backup']=\"".htmlspecialchars($_POST['paths#backup'])."\";\n"); 
     fwrite($handle,"\$script['system']['time_adjust']=\"".htmlspecialchars($_POST['system#time_adjust'])."\";\n\n");
     fwrite($handle,"\$script['system']['language']=\"".htmlspecialchars($_POST['system#language'])."\";\n\n");
   fwrite($handle,"?>");
   fclose($handle);
}

function ReadConfiguration($wrapper)
{
    return $wrapper;
}



?>